#%RAML 1.0 ResourceType

traits:
  headers: !include /trait/headers-trait.raml

types:
  commonError: !include /dataType/common-error-dataType.raml
  commonWeatherResponse: !include /dataType/common-weather-response-dataType.raml